www.france24.com:
- /html/body/main/div[3]/article/h1
- /html/body/main/div[3]/article/p
- /html/body/main/div[3]/article/div[3]/p/span[1]/time
- /html/body/main/div[3]/article/div[5]/div/div[1]/div/a[1]
- /html/body/main/div[3]/article/div[4]/figure/div/img
- /html/body/main/div[3]/article/div[6]
- /html/body/main/div[3]/nav/ol/li[2]/a
- 30

www.lemonde.fr:
- /html/body/main/section[1]/section/header/div/div/h1
- /html/body/main/section[1]/section/header/div/div/p
- /html/body/main/section[1]/section/header/div/section/span
- /html/body/main/section[1]/section/header/div/p/span/a/span
- /html/body/main/section[1]/section/section/article/figure/img
- /html/body/main/section[1]/section/section/article/p[1]
- /html/body/main/section[1]/section/header/div/ul[1]/li/a
- 30

www.mic.com: 
- /html/body/div/div[1]/article[1]/div[1]/div/div[2]/h1
- /html/body/div/div[1]/article[1]/div[2]/div/p[1]
- /html/body/div/div[1]/article[1]/div[1]/div/div[3]/div/div[3]/time
- /html/body/div/div[1]/article[1]/div[1]/div/div[3]/div/div[2]/a
- /html/body/div/div[1]/article[1]/div[1]/div/div[1]/img
- /html/body/div/div[1]/article[1]/div[2]/div
- /html/body/main/section[1]/section/header/div/ul[1]/li/a
- 30

www.standard.co.uk: 
- //*[@id="frameInner"]/article/header/div/div/h1
- //*[@id="main"]/div[1]/p
- //*[@id="frameInner"]/article/div[3]/div/div[1]/div/div/div[2]/amp-timeago/time
- //*[@id="frameInner"]/article/div[3]/div/div[1]/div/div/div[1]/a
- //*[@id="frameInner"]/article/header/div/figure/amp-img/img
- //*[@id="main"]
- /html/body/main/section[1]/section/header/div/ul[1]/li/a
- 30


www.arabnews.com: 
- //*[@id="content-articles"]/div[1]/article/div[1]/h1
- //*[@id="content-articles"]/div[1]/article/div[3]/div[2]/div[1]/div[3]
- //*[@id="content-articles"]/div[1]/article/div[3]/div[2]/div[1]/div[4]/div[3]
- //*[@id="content-articles"]/div[1]/article/div[3]/div[2]/div[1]/div[4]/div[2]
- //*[@id="content-articles"]/div[1]/article/div[2]/div[1]/div/div/div/div/div/div[1]/img
- //*[@id="content-articles"]/div[1]/article/div[3]/div[2]/div[1]/div[5]/div[2]/div/div/p[1]
- /html/body/main/section[1]/section/header/div/ul[1]/li/a
- 30

www.irishexaminer.com: 
- //*[@id="body"]/div[3]/div/div[2]/div/div/div[2]/article/div[1]/figure/h1/span
- //*[@id="body"]/div[3]/div/div[2]/div/div/div[2]/article/div[1]/figure/div
- //*[@id="body"]/div[3]/div/div[2]/div/div/div[2]/article/div[3]
- //*[@id="body"]/div[3]/div/div[2]/div/div/div[2]/article/div[4]/div
- //*[@id="body"]/div[3]/div/div[2]/div/div/div[2]/article/div[1]/figure/picture/img
- //*[@id="body"]/div[3]/div/div[2]/div/div/div[2]/article/div[5]/div[1]
- /html/body/main/section[1]/section/header/div/ul[1]/li/a
- 30
